### ISSUE TITLE
Unexpected leading \x00 byte after patch

### ISSUE THREAD

**Issue by gurupras** [balena-os/librsync-go#12]
First, thank you for writing and maintaining this library.

I'm not familiar with librsync, so I'm trying to figure out how to use this library from the existing tests. I came up with the following test of my own, which I expect to pass but it fails instead.

```go
import (
	"bytes"
	"io/ioutil"
	"strings"
	"testing"

	"github.com/balena-os/librsync-go"
	"github.com/stretchr/testify/require"
)

func TestLibRsync(t *testing.T) {
	require := require.New(t)

	baseStr := "Hello World"
	newStr := "Hollywood"

	srcReader := strings.NewReader(baseStr)
	newReader := strings.NewReader(newStr)

	sig, err := librsync.Signature(srcReader, ioutil.Discard, 512, 32, librsync.BLAKE2_SIG_MAGIC)
	require.Nil(err)

	var delta bytes.Buffer
	err = librsync.Delta(sig, newReader, &delta)
	require.Nil(err)

	result := bytes.NewBuffer(nil)

	err = librsync.Patch(strings.NewReader(baseStr), &delta, result)
	require.Nil(err)

	require.Equal(newStr, result.String())
}
```

```
=== RUN   TestLibRsync
    rsync_test.go:34: 
        	Error Trace:	rsync_test.go:34
        	Error:      	Not equal: 
        	            	expected: "Hollywood"
        	            	actual  : "\x00Hollywood"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-Hollywood
        	            	+Hollywood
        	Test:       	TestLibRsync
--- FAIL: TestLibRsync (0.00s)
FAIL
exit status 1
```

What am I doing wrong?

**Comment by lmbarros** [comment]
Thanks for bringing this up, @gurupras!

As far as I can tell, you are not doing anything wrong. There is a known bug with librsync-go that makes it fail when the block size (512 bytes in your test case) is larger than the new data (`len("Hollywood") == 9`).

This is fixed on https://github.com/balena-os/librsync-go/pull/10, which we hope to merge soonish. (If you want a quick temporary patch, I believe you can just take the changes made on `delta.go`. Should work.)
