### ISSUE TITLE
In-place updates

### ISSUE THREAD

**Issue by gurupras** [balena-os/librsync-go#13]
Any chance this library can be used for in-place file updates? It looks like it's 95% there already.
I tried looking at the code to understand what's going on in the `Patch` stage, but my understanding of the following code is that it's doing a full replacement.

```golang
switch cmd.Kind {
	default:
		return fmt.Errorf("Bogus command %x", cmd.Kind)
	case KIND_LITERAL:
		io.CopyN(out, delta, param1)
	case KIND_COPY:
		base.Seek(param1, io.SeekStart)
		io.CopyN(out, base, param2)
	case KIND_END:
		return nil
	}
}
```

Would be tremendously helpful if you could provide a method or an example of doing in-place updates to a file.

**Comment by lmbarros** [comment]
@gurupras, I don't think it would be possible. The delta is a series of commands, either `LITERAL`s ("here's some literal data that must be copied to the destination file") or `COPY`s ("copy some data from the old file to the destination file"). (There's also the `END` command, that marks the end of the delta.)

Imagine you have:

* Old file (basis) contents: `1234`
* New file (target) contents: `abcde1234`

The delta would look like:

1. `LITERAL abcde`
2. `COPY 4 bytes starting from offset 0`

If you run the first command in place, you'd overwrite data that is referenced in the second command, and the patch would generate an incorrect file.
